#include <tree_sitter/parser.h>

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 126
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 53
#define ALIAS_COUNT 0
#define TOKEN_COUNT 26
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 7
#define PRODUCTION_ID_COUNT 1

enum {
  anon_sym_ATpage = 1,
  aux_sym_route_token1 = 2,
  anon_sym_EQ = 3,
  anon_sym_LT = 4,
  anon_sym_GT = 5,
  anon_sym_LT_SLASH = 6,
  anon_sym_AT = 7,
  anon_sym_LPAREN = 8,
  anon_sym_RPAREN = 9,
  anon_sym_ATif = 10,
  anon_sym_LBRACE = 11,
  anon_sym_RBRACE = 12,
  anon_sym_ATwhile = 13,
  anon_sym_AT_LBRACE = 14,
  anon_sym_SEMI = 15,
  anon_sym_var = 16,
  anon_sym_PLUS = 17,
  anon_sym_DASH = 18,
  anon_sym_COMMA = 19,
  anon_sym_DOT = 20,
  sym_identifier = 21,
  sym_word = 22,
  sym_tag_name = 23,
  sym_number = 24,
  sym_non_word = 25,
  sym_document = 26,
  sym__markup = 27,
  sym_route_declaration = 28,
  sym_route = 29,
  sym_element = 30,
  sym_attribute = 31,
  sym_start_tag = 32,
  sym_end_tag = 33,
  sym__code = 34,
  sym_interpolated_expression = 35,
  sym_interpolated_if_statement = 36,
  sym_interpolated_while_statement = 37,
  sym_interpolated_code_block = 38,
  sym__expression = 39,
  sym__simple_expression = 40,
  sym__statement = 41,
  sym_variable_declaration = 42,
  sym_type_specifier = 43,
  sym_expression_statement = 44,
  sym_binary_expression = 45,
  sym_call_expression = 46,
  sym_simple_call_expression = 47,
  sym_member_expression = 48,
  sym_simple_member_expression = 49,
  sym_string = 50,
  aux_sym_document_repeat1 = 51,
  aux_sym_call_expression_repeat1 = 52,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_ATpage] = "@page",
  [aux_sym_route_token1] = "route_token1",
  [anon_sym_EQ] = "=",
  [anon_sym_LT] = "<",
  [anon_sym_GT] = ">",
  [anon_sym_LT_SLASH] = "</",
  [anon_sym_AT] = "@",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [anon_sym_ATif] = "@if",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_ATwhile] = "@while",
  [anon_sym_AT_LBRACE] = "@{",
  [anon_sym_SEMI] = ";",
  [anon_sym_var] = "var",
  [anon_sym_PLUS] = "+",
  [anon_sym_DASH] = "-",
  [anon_sym_COMMA] = ",",
  [anon_sym_DOT] = ".",
  [sym_identifier] = "identifier",
  [sym_word] = "word",
  [sym_tag_name] = "tag_name",
  [sym_number] = "number",
  [sym_non_word] = "non_word",
  [sym_document] = "document",
  [sym__markup] = "_markup",
  [sym_route_declaration] = "route_declaration",
  [sym_route] = "route",
  [sym_element] = "element",
  [sym_attribute] = "attribute",
  [sym_start_tag] = "start_tag",
  [sym_end_tag] = "end_tag",
  [sym__code] = "_code",
  [sym_interpolated_expression] = "interpolated_expression",
  [sym_interpolated_if_statement] = "interpolated_if_statement",
  [sym_interpolated_while_statement] = "interpolated_while_statement",
  [sym_interpolated_code_block] = "interpolated_code_block",
  [sym__expression] = "_expression",
  [sym__simple_expression] = "_simple_expression",
  [sym__statement] = "_statement",
  [sym_variable_declaration] = "variable_declaration",
  [sym_type_specifier] = "type_specifier",
  [sym_expression_statement] = "expression_statement",
  [sym_binary_expression] = "binary_expression",
  [sym_call_expression] = "call_expression",
  [sym_simple_call_expression] = "simple_call_expression",
  [sym_member_expression] = "member_expression",
  [sym_simple_member_expression] = "simple_member_expression",
  [sym_string] = "string",
  [aux_sym_document_repeat1] = "document_repeat1",
  [aux_sym_call_expression_repeat1] = "call_expression_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_ATpage] = anon_sym_ATpage,
  [aux_sym_route_token1] = aux_sym_route_token1,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_LT] = anon_sym_LT,
  [anon_sym_GT] = anon_sym_GT,
  [anon_sym_LT_SLASH] = anon_sym_LT_SLASH,
  [anon_sym_AT] = anon_sym_AT,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_ATif] = anon_sym_ATif,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_ATwhile] = anon_sym_ATwhile,
  [anon_sym_AT_LBRACE] = anon_sym_AT_LBRACE,
  [anon_sym_SEMI] = anon_sym_SEMI,
  [anon_sym_var] = anon_sym_var,
  [anon_sym_PLUS] = anon_sym_PLUS,
  [anon_sym_DASH] = anon_sym_DASH,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_DOT] = anon_sym_DOT,
  [sym_identifier] = sym_identifier,
  [sym_word] = sym_word,
  [sym_tag_name] = sym_tag_name,
  [sym_number] = sym_number,
  [sym_non_word] = sym_non_word,
  [sym_document] = sym_document,
  [sym__markup] = sym__markup,
  [sym_route_declaration] = sym_route_declaration,
  [sym_route] = sym_route,
  [sym_element] = sym_element,
  [sym_attribute] = sym_attribute,
  [sym_start_tag] = sym_start_tag,
  [sym_end_tag] = sym_end_tag,
  [sym__code] = sym__code,
  [sym_interpolated_expression] = sym_interpolated_expression,
  [sym_interpolated_if_statement] = sym_interpolated_if_statement,
  [sym_interpolated_while_statement] = sym_interpolated_while_statement,
  [sym_interpolated_code_block] = sym_interpolated_code_block,
  [sym__expression] = sym__expression,
  [sym__simple_expression] = sym__simple_expression,
  [sym__statement] = sym__statement,
  [sym_variable_declaration] = sym_variable_declaration,
  [sym_type_specifier] = sym_type_specifier,
  [sym_expression_statement] = sym_expression_statement,
  [sym_binary_expression] = sym_binary_expression,
  [sym_call_expression] = sym_call_expression,
  [sym_simple_call_expression] = sym_simple_call_expression,
  [sym_member_expression] = sym_member_expression,
  [sym_simple_member_expression] = sym_simple_member_expression,
  [sym_string] = sym_string,
  [aux_sym_document_repeat1] = aux_sym_document_repeat1,
  [aux_sym_call_expression_repeat1] = aux_sym_call_expression_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_ATpage] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_route_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT_SLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_AT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_ATif] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_ATwhile] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_AT_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SEMI] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_var] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PLUS] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOT] = {
    .visible = true,
    .named = false,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_word] = {
    .visible = true,
    .named = true,
  },
  [sym_tag_name] = {
    .visible = true,
    .named = true,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [sym_non_word] = {
    .visible = true,
    .named = true,
  },
  [sym_document] = {
    .visible = true,
    .named = true,
  },
  [sym__markup] = {
    .visible = false,
    .named = true,
  },
  [sym_route_declaration] = {
    .visible = true,
    .named = true,
  },
  [sym_route] = {
    .visible = true,
    .named = true,
  },
  [sym_element] = {
    .visible = true,
    .named = true,
  },
  [sym_attribute] = {
    .visible = true,
    .named = true,
  },
  [sym_start_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_end_tag] = {
    .visible = true,
    .named = true,
  },
  [sym__code] = {
    .visible = false,
    .named = true,
  },
  [sym_interpolated_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_interpolated_if_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_interpolated_while_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_interpolated_code_block] = {
    .visible = true,
    .named = true,
  },
  [sym__expression] = {
    .visible = false,
    .named = true,
  },
  [sym__simple_expression] = {
    .visible = false,
    .named = true,
  },
  [sym__statement] = {
    .visible = false,
    .named = true,
  },
  [sym_variable_declaration] = {
    .visible = true,
    .named = true,
  },
  [sym_type_specifier] = {
    .visible = true,
    .named = true,
  },
  [sym_expression_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_binary_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_call_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_simple_call_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_member_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_simple_member_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_document_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_call_expression_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 4,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 7,
  [11] = 9,
  [12] = 8,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 22,
  [32] = 32,
  [33] = 33,
  [34] = 27,
  [35] = 24,
  [36] = 32,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 38,
  [41] = 39,
  [42] = 42,
  [43] = 42,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 49,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 58,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 60,
  [64] = 56,
  [65] = 61,
  [66] = 13,
  [67] = 67,
  [68] = 15,
  [69] = 69,
  [70] = 14,
  [71] = 71,
  [72] = 69,
  [73] = 73,
  [74] = 16,
  [75] = 67,
  [76] = 17,
  [77] = 77,
  [78] = 25,
  [79] = 79,
  [80] = 77,
  [81] = 81,
  [82] = 82,
  [83] = 18,
  [84] = 79,
  [85] = 23,
  [86] = 30,
  [87] = 81,
  [88] = 88,
  [89] = 89,
  [90] = 19,
  [91] = 91,
  [92] = 26,
  [93] = 93,
  [94] = 94,
  [95] = 95,
  [96] = 96,
  [97] = 20,
  [98] = 21,
  [99] = 99,
  [100] = 100,
  [101] = 101,
  [102] = 101,
  [103] = 88,
  [104] = 104,
  [105] = 105,
  [106] = 106,
  [107] = 107,
  [108] = 108,
  [109] = 109,
  [110] = 94,
  [111] = 93,
  [112] = 112,
  [113] = 113,
  [114] = 113,
  [115] = 89,
  [116] = 112,
  [117] = 117,
  [118] = 100,
  [119] = 99,
  [120] = 104,
  [121] = 121,
  [122] = 28,
  [123] = 29,
  [124] = 106,
  [125] = 107,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(17);
      if (lookahead == '"') ADVANCE(1);
      if (lookahead == '(') ADVANCE(25);
      if (lookahead == ')') ADVANCE(26);
      if (lookahead == '+') ADVANCE(35);
      if (lookahead == ',') ADVANCE(38);
      if (lookahead == '-') ADVANCE(36);
      if (lookahead == '.') ADVANCE(39);
      if (lookahead == ';') ADVANCE(32);
      if (lookahead == '<') ADVANCE(21);
      if (lookahead == '=') ADVANCE(20);
      if (lookahead == '>') ADVANCE(22);
      if (lookahead == '@') ADVANCE(24);
      if (lookahead == 'v') ADVANCE(3);
      if (lookahead == '{') ADVANCE(28);
      if (lookahead == '}') ADVANCE(29);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(0)
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(48);
      END_STATE();
    case 1:
      if (lookahead == '"') ADVANCE(19);
      if (lookahead != 0) ADVANCE(1);
      END_STATE();
    case 2:
      if (lookahead == '>') ADVANCE(22);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(2)
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(46);
      END_STATE();
    case 3:
      if (lookahead == 'a') ADVANCE(12);
      END_STATE();
    case 4:
      if (lookahead == 'a') ADVANCE(8);
      END_STATE();
    case 5:
      if (lookahead == 'e') ADVANCE(18);
      END_STATE();
    case 6:
      if (lookahead == 'e') ADVANCE(30);
      END_STATE();
    case 7:
      if (lookahead == 'f') ADVANCE(27);
      END_STATE();
    case 8:
      if (lookahead == 'g') ADVANCE(5);
      END_STATE();
    case 9:
      if (lookahead == 'h') ADVANCE(10);
      END_STATE();
    case 10:
      if (lookahead == 'i') ADVANCE(11);
      END_STATE();
    case 11:
      if (lookahead == 'l') ADVANCE(6);
      END_STATE();
    case 12:
      if (lookahead == 'r') ADVANCE(33);
      END_STATE();
    case 13:
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(13)
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(47);
      END_STATE();
    case 14:
      if (eof) ADVANCE(17);
      if (lookahead == '(') ADVANCE(25);
      if (lookahead == '.') ADVANCE(39);
      if (lookahead == '<') ADVANCE(21);
      if (lookahead == '@') ADVANCE(24);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(50);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(46);
      if (lookahead != 0 &&
          lookahead != 7) ADVANCE(49);
      END_STATE();
    case 15:
      if (eof) ADVANCE(17);
      if (lookahead == '<') ADVANCE(21);
      if (lookahead == '=') ADVANCE(20);
      if (lookahead == '@') ADVANCE(24);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(51);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(46);
      if (lookahead != 0 &&
          lookahead != 7) ADVANCE(49);
      END_STATE();
    case 16:
      if (eof) ADVANCE(17);
      if (lookahead == '<') ADVANCE(21);
      if (lookahead == '@') ADVANCE(24);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(52);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(46);
      if (lookahead != 0 &&
          lookahead != 7) ADVANCE(49);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(anon_sym_ATpage);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(aux_sym_route_token1);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(anon_sym_LT);
      if (lookahead == '/') ADVANCE(23);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(anon_sym_GT);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(anon_sym_LT_SLASH);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(anon_sym_AT);
      if (lookahead == 'i') ADVANCE(7);
      if (lookahead == 'p') ADVANCE(4);
      if (lookahead == 'w') ADVANCE(9);
      if (lookahead == '{') ADVANCE(31);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(anon_sym_ATif);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(anon_sym_ATwhile);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(anon_sym_AT_LBRACE);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(anon_sym_SEMI);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(anon_sym_var);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(anon_sym_var);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(45);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(anon_sym_PLUS);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(anon_sym_DASH);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(anon_sym_DASH);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(45);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(anon_sym_DOT);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '-') ADVANCE(37);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(45);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'a') ADVANCE(42);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(45);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'r') ADVANCE(34);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(45);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'v') ADVANCE(41);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(44);
      if (lookahead == '-' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(45);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(44);
      if (lookahead == '-' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(45);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(45);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(sym_word);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(46);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(sym_tag_name);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(47);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(sym_number);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(48);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(sym_non_word);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(sym_non_word);
      if (lookahead == '(') ADVANCE(25);
      if (lookahead == '.') ADVANCE(39);
      if (lookahead == '<') ADVANCE(21);
      if (lookahead == '@') ADVANCE(24);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(50);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(46);
      if (lookahead != 0 &&
          lookahead != 7) ADVANCE(49);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(sym_non_word);
      if (lookahead == '<') ADVANCE(21);
      if (lookahead == '=') ADVANCE(20);
      if (lookahead == '@') ADVANCE(24);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(51);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(46);
      if (lookahead != 0 &&
          lookahead != 7) ADVANCE(49);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(sym_non_word);
      if (lookahead == '<') ADVANCE(21);
      if (lookahead == '@') ADVANCE(24);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(52);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(46);
      if (lookahead != 0 &&
          lookahead != 7) ADVANCE(49);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 16},
  [2] = {.lex_state = 16},
  [3] = {.lex_state = 16},
  [4] = {.lex_state = 16},
  [5] = {.lex_state = 16},
  [6] = {.lex_state = 16},
  [7] = {.lex_state = 43},
  [8] = {.lex_state = 43},
  [9] = {.lex_state = 43},
  [10] = {.lex_state = 43},
  [11] = {.lex_state = 43},
  [12] = {.lex_state = 43},
  [13] = {.lex_state = 14},
  [14] = {.lex_state = 14},
  [15] = {.lex_state = 14},
  [16] = {.lex_state = 14},
  [17] = {.lex_state = 14},
  [18] = {.lex_state = 15},
  [19] = {.lex_state = 16},
  [20] = {.lex_state = 16},
  [21] = {.lex_state = 16},
  [22] = {.lex_state = 16},
  [23] = {.lex_state = 16},
  [24] = {.lex_state = 16},
  [25] = {.lex_state = 16},
  [26] = {.lex_state = 16},
  [27] = {.lex_state = 16},
  [28] = {.lex_state = 16},
  [29] = {.lex_state = 16},
  [30] = {.lex_state = 16},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 44},
  [33] = {.lex_state = 44},
  [34] = {.lex_state = 16},
  [35] = {.lex_state = 16},
  [36] = {.lex_state = 44},
  [37] = {.lex_state = 44},
  [38] = {.lex_state = 44},
  [39] = {.lex_state = 44},
  [40] = {.lex_state = 44},
  [41] = {.lex_state = 44},
  [42] = {.lex_state = 44},
  [43] = {.lex_state = 44},
  [44] = {.lex_state = 44},
  [45] = {.lex_state = 44},
  [46] = {.lex_state = 0},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 0},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 0},
  [51] = {.lex_state = 0},
  [52] = {.lex_state = 0},
  [53] = {.lex_state = 0},
  [54] = {.lex_state = 0},
  [55] = {.lex_state = 40},
  [56] = {.lex_state = 0},
  [57] = {.lex_state = 0},
  [58] = {.lex_state = 44},
  [59] = {.lex_state = 44},
  [60] = {.lex_state = 0},
  [61] = {.lex_state = 0},
  [62] = {.lex_state = 0},
  [63] = {.lex_state = 0},
  [64] = {.lex_state = 0},
  [65] = {.lex_state = 0},
  [66] = {.lex_state = 0},
  [67] = {.lex_state = 2},
  [68] = {.lex_state = 0},
  [69] = {.lex_state = 0},
  [70] = {.lex_state = 0},
  [71] = {.lex_state = 0},
  [72] = {.lex_state = 0},
  [73] = {.lex_state = 0},
  [74] = {.lex_state = 0},
  [75] = {.lex_state = 2},
  [76] = {.lex_state = 0},
  [77] = {.lex_state = 0},
  [78] = {.lex_state = 0},
  [79] = {.lex_state = 0},
  [80] = {.lex_state = 0},
  [81] = {.lex_state = 0},
  [82] = {.lex_state = 0},
  [83] = {.lex_state = 0},
  [84] = {.lex_state = 0},
  [85] = {.lex_state = 0},
  [86] = {.lex_state = 0},
  [87] = {.lex_state = 0},
  [88] = {.lex_state = 0},
  [89] = {.lex_state = 44},
  [90] = {.lex_state = 0},
  [91] = {.lex_state = 0},
  [92] = {.lex_state = 0},
  [93] = {.lex_state = 0},
  [94] = {.lex_state = 0},
  [95] = {.lex_state = 44},
  [96] = {.lex_state = 0},
  [97] = {.lex_state = 0},
  [98] = {.lex_state = 0},
  [99] = {.lex_state = 0},
  [100] = {.lex_state = 0},
  [101] = {.lex_state = 0},
  [102] = {.lex_state = 0},
  [103] = {.lex_state = 0},
  [104] = {.lex_state = 0},
  [105] = {.lex_state = 0},
  [106] = {.lex_state = 0},
  [107] = {.lex_state = 0},
  [108] = {.lex_state = 44},
  [109] = {.lex_state = 0},
  [110] = {.lex_state = 0},
  [111] = {.lex_state = 0},
  [112] = {.lex_state = 13},
  [113] = {.lex_state = 13},
  [114] = {.lex_state = 13},
  [115] = {.lex_state = 44},
  [116] = {.lex_state = 13},
  [117] = {.lex_state = 44},
  [118] = {.lex_state = 0},
  [119] = {.lex_state = 0},
  [120] = {.lex_state = 0},
  [121] = {.lex_state = 0},
  [122] = {.lex_state = 0},
  [123] = {.lex_state = 0},
  [124] = {.lex_state = 0},
  [125] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_ATpage] = ACTIONS(1),
    [aux_sym_route_token1] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_LT] = ACTIONS(1),
    [anon_sym_GT] = ACTIONS(1),
    [anon_sym_LT_SLASH] = ACTIONS(1),
    [anon_sym_AT] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_ATif] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_ATwhile] = ACTIONS(1),
    [anon_sym_AT_LBRACE] = ACTIONS(1),
    [anon_sym_SEMI] = ACTIONS(1),
    [anon_sym_var] = ACTIONS(1),
    [anon_sym_PLUS] = ACTIONS(1),
    [anon_sym_DASH] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_DOT] = ACTIONS(1),
    [sym_number] = ACTIONS(1),
  },
  [1] = {
    [sym_document] = STATE(105),
    [sym__markup] = STATE(2),
    [sym_route_declaration] = STATE(2),
    [sym_element] = STATE(2),
    [sym_attribute] = STATE(2),
    [sym_start_tag] = STATE(4),
    [sym_end_tag] = STATE(2),
    [sym_interpolated_expression] = STATE(2),
    [sym_interpolated_if_statement] = STATE(2),
    [sym_interpolated_while_statement] = STATE(2),
    [sym_interpolated_code_block] = STATE(2),
    [aux_sym_document_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(3),
    [anon_sym_ATpage] = ACTIONS(5),
    [anon_sym_LT] = ACTIONS(7),
    [anon_sym_LT_SLASH] = ACTIONS(9),
    [anon_sym_AT] = ACTIONS(11),
    [anon_sym_ATif] = ACTIONS(13),
    [anon_sym_ATwhile] = ACTIONS(15),
    [anon_sym_AT_LBRACE] = ACTIONS(17),
    [sym_word] = ACTIONS(19),
    [sym_non_word] = ACTIONS(21),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 12,
    ACTIONS(5), 1,
      anon_sym_ATpage,
    ACTIONS(7), 1,
      anon_sym_LT,
    ACTIONS(9), 1,
      anon_sym_LT_SLASH,
    ACTIONS(11), 1,
      anon_sym_AT,
    ACTIONS(13), 1,
      anon_sym_ATif,
    ACTIONS(15), 1,
      anon_sym_ATwhile,
    ACTIONS(17), 1,
      anon_sym_AT_LBRACE,
    ACTIONS(19), 1,
      sym_word,
    ACTIONS(23), 1,
      ts_builtin_sym_end,
    ACTIONS(25), 1,
      sym_non_word,
    STATE(4), 1,
      sym_start_tag,
    STATE(3), 10,
      sym__markup,
      sym_route_declaration,
      sym_element,
      sym_attribute,
      sym_end_tag,
      sym_interpolated_expression,
      sym_interpolated_if_statement,
      sym_interpolated_while_statement,
      sym_interpolated_code_block,
      aux_sym_document_repeat1,
  [46] = 12,
    ACTIONS(27), 1,
      ts_builtin_sym_end,
    ACTIONS(29), 1,
      anon_sym_ATpage,
    ACTIONS(32), 1,
      anon_sym_LT,
    ACTIONS(35), 1,
      anon_sym_LT_SLASH,
    ACTIONS(38), 1,
      anon_sym_AT,
    ACTIONS(41), 1,
      anon_sym_ATif,
    ACTIONS(44), 1,
      anon_sym_ATwhile,
    ACTIONS(47), 1,
      anon_sym_AT_LBRACE,
    ACTIONS(50), 1,
      sym_word,
    ACTIONS(53), 1,
      sym_non_word,
    STATE(4), 1,
      sym_start_tag,
    STATE(3), 10,
      sym__markup,
      sym_route_declaration,
      sym_element,
      sym_attribute,
      sym_end_tag,
      sym_interpolated_expression,
      sym_interpolated_if_statement,
      sym_interpolated_while_statement,
      sym_interpolated_code_block,
      aux_sym_document_repeat1,
  [92] = 12,
    ACTIONS(56), 1,
      ts_builtin_sym_end,
    ACTIONS(58), 1,
      anon_sym_ATpage,
    ACTIONS(60), 1,
      anon_sym_LT,
    ACTIONS(62), 1,
      anon_sym_LT_SLASH,
    ACTIONS(64), 1,
      anon_sym_AT,
    ACTIONS(66), 1,
      anon_sym_ATif,
    ACTIONS(68), 1,
      anon_sym_ATwhile,
    ACTIONS(70), 1,
      anon_sym_AT_LBRACE,
    ACTIONS(72), 1,
      sym_word,
    ACTIONS(74), 1,
      sym_non_word,
    STATE(6), 1,
      sym_start_tag,
    STATE(80), 9,
      sym__markup,
      sym_route_declaration,
      sym_element,
      sym_attribute,
      sym_end_tag,
      sym_interpolated_expression,
      sym_interpolated_if_statement,
      sym_interpolated_while_statement,
      sym_interpolated_code_block,
  [137] = 11,
    ACTIONS(58), 1,
      anon_sym_ATpage,
    ACTIONS(60), 1,
      anon_sym_LT,
    ACTIONS(62), 1,
      anon_sym_LT_SLASH,
    ACTIONS(64), 1,
      anon_sym_AT,
    ACTIONS(66), 1,
      anon_sym_ATif,
    ACTIONS(68), 1,
      anon_sym_ATwhile,
    ACTIONS(70), 1,
      anon_sym_AT_LBRACE,
    ACTIONS(72), 1,
      sym_word,
    ACTIONS(76), 1,
      sym_non_word,
    STATE(6), 1,
      sym_start_tag,
    STATE(77), 9,
      sym__markup,
      sym_route_declaration,
      sym_element,
      sym_attribute,
      sym_end_tag,
      sym_interpolated_expression,
      sym_interpolated_if_statement,
      sym_interpolated_while_statement,
      sym_interpolated_code_block,
  [179] = 11,
    ACTIONS(58), 1,
      anon_sym_ATpage,
    ACTIONS(60), 1,
      anon_sym_LT,
    ACTIONS(62), 1,
      anon_sym_LT_SLASH,
    ACTIONS(64), 1,
      anon_sym_AT,
    ACTIONS(66), 1,
      anon_sym_ATif,
    ACTIONS(68), 1,
      anon_sym_ATwhile,
    ACTIONS(70), 1,
      anon_sym_AT_LBRACE,
    ACTIONS(72), 1,
      sym_word,
    ACTIONS(76), 1,
      sym_non_word,
    STATE(6), 1,
      sym_start_tag,
    STATE(77), 9,
      sym__markup,
      sym_route_declaration,
      sym_element,
      sym_attribute,
      sym_end_tag,
      sym_interpolated_expression,
      sym_interpolated_if_statement,
      sym_interpolated_while_statement,
      sym_interpolated_code_block,
  [221] = 9,
    ACTIONS(60), 1,
      anon_sym_LT,
    ACTIONS(78), 1,
      aux_sym_route_token1,
    ACTIONS(80), 1,
      anon_sym_var,
    ACTIONS(82), 1,
      sym_identifier,
    ACTIONS(84), 1,
      sym_number,
    STATE(5), 1,
      sym_start_tag,
    STATE(117), 1,
      sym_type_specifier,
    STATE(57), 5,
      sym__expression,
      sym_binary_expression,
      sym_call_expression,
      sym_member_expression,
      sym_string,
    STATE(103), 5,
      sym_element,
      sym__code,
      sym__statement,
      sym_variable_declaration,
      sym_expression_statement,
  [257] = 9,
    ACTIONS(60), 1,
      anon_sym_LT,
    ACTIONS(78), 1,
      aux_sym_route_token1,
    ACTIONS(80), 1,
      anon_sym_var,
    ACTIONS(82), 1,
      sym_identifier,
    ACTIONS(84), 1,
      sym_number,
    STATE(5), 1,
      sym_start_tag,
    STATE(117), 1,
      sym_type_specifier,
    STATE(57), 5,
      sym__expression,
      sym_binary_expression,
      sym_call_expression,
      sym_member_expression,
      sym_string,
    STATE(111), 5,
      sym_element,
      sym__code,
      sym__statement,
      sym_variable_declaration,
      sym_expression_statement,
  [293] = 9,
    ACTIONS(60), 1,
      anon_sym_LT,
    ACTIONS(78), 1,
      aux_sym_route_token1,
    ACTIONS(80), 1,
      anon_sym_var,
    ACTIONS(82), 1,
      sym_identifier,
    ACTIONS(84), 1,
      sym_number,
    STATE(5), 1,
      sym_start_tag,
    STATE(117), 1,
      sym_type_specifier,
    STATE(57), 5,
      sym__expression,
      sym_binary_expression,
      sym_call_expression,
      sym_member_expression,
      sym_string,
    STATE(110), 5,
      sym_element,
      sym__code,
      sym__statement,
      sym_variable_declaration,
      sym_expression_statement,
  [329] = 9,
    ACTIONS(60), 1,
      anon_sym_LT,
    ACTIONS(78), 1,
      aux_sym_route_token1,
    ACTIONS(80), 1,
      anon_sym_var,
    ACTIONS(82), 1,
      sym_identifier,
    ACTIONS(84), 1,
      sym_number,
    STATE(5), 1,
      sym_start_tag,
    STATE(117), 1,
      sym_type_specifier,
    STATE(57), 5,
      sym__expression,
      sym_binary_expression,
      sym_call_expression,
      sym_member_expression,
      sym_string,
    STATE(88), 5,
      sym_element,
      sym__code,
      sym__statement,
      sym_variable_declaration,
      sym_expression_statement,
  [365] = 9,
    ACTIONS(60), 1,
      anon_sym_LT,
    ACTIONS(78), 1,
      aux_sym_route_token1,
    ACTIONS(80), 1,
      anon_sym_var,
    ACTIONS(82), 1,
      sym_identifier,
    ACTIONS(84), 1,
      sym_number,
    STATE(5), 1,
      sym_start_tag,
    STATE(117), 1,
      sym_type_specifier,
    STATE(57), 5,
      sym__expression,
      sym_binary_expression,
      sym_call_expression,
      sym_member_expression,
      sym_string,
    STATE(94), 5,
      sym_element,
      sym__code,
      sym__statement,
      sym_variable_declaration,
      sym_expression_statement,
  [401] = 9,
    ACTIONS(60), 1,
      anon_sym_LT,
    ACTIONS(78), 1,
      aux_sym_route_token1,
    ACTIONS(80), 1,
      anon_sym_var,
    ACTIONS(82), 1,
      sym_identifier,
    ACTIONS(84), 1,
      sym_number,
    STATE(5), 1,
      sym_start_tag,
    STATE(117), 1,
      sym_type_specifier,
    STATE(57), 5,
      sym__expression,
      sym_binary_expression,
      sym_call_expression,
      sym_member_expression,
      sym_string,
    STATE(93), 5,
      sym_element,
      sym__code,
      sym__statement,
      sym_variable_declaration,
      sym_expression_statement,
  [437] = 2,
    ACTIONS(86), 1,
      ts_builtin_sym_end,
    ACTIONS(88), 11,
      anon_sym_ATpage,
      anon_sym_LT,
      anon_sym_LT_SLASH,
      anon_sym_AT,
      anon_sym_LPAREN,
      anon_sym_ATif,
      anon_sym_ATwhile,
      anon_sym_AT_LBRACE,
      anon_sym_DOT,
      sym_word,
      sym_non_word,
  [454] = 2,
    ACTIONS(90), 1,
      ts_builtin_sym_end,
    ACTIONS(92), 11,
      anon_sym_ATpage,
      anon_sym_LT,
      anon_sym_LT_SLASH,
      anon_sym_AT,
      anon_sym_LPAREN,
      anon_sym_ATif,
      anon_sym_ATwhile,
      anon_sym_AT_LBRACE,
      anon_sym_DOT,
      sym_word,
      sym_non_word,
  [471] = 2,
    ACTIONS(94), 1,
      ts_builtin_sym_end,
    ACTIONS(96), 11,
      anon_sym_ATpage,
      anon_sym_LT,
      anon_sym_LT_SLASH,
      anon_sym_AT,
      anon_sym_LPAREN,
      anon_sym_ATif,
      anon_sym_ATwhile,
      anon_sym_AT_LBRACE,
      anon_sym_DOT,
      sym_word,
      sym_non_word,
  [488] = 2,
    ACTIONS(98), 1,
      ts_builtin_sym_end,
    ACTIONS(100), 11,
      anon_sym_ATpage,
      anon_sym_LT,
      anon_sym_LT_SLASH,
      anon_sym_AT,
      anon_sym_LPAREN,
      anon_sym_ATif,
      anon_sym_ATwhile,
      anon_sym_AT_LBRACE,
      anon_sym_DOT,
      sym_word,
      sym_non_word,
  [505] = 4,
    ACTIONS(102), 1,
      ts_builtin_sym_end,
    ACTIONS(106), 1,
      anon_sym_LPAREN,
    ACTIONS(108), 1,
      anon_sym_DOT,
    ACTIONS(104), 9,
      anon_sym_ATpage,
      anon_sym_LT,
      anon_sym_LT_SLASH,
      anon_sym_AT,
      anon_sym_ATif,
      anon_sym_ATwhile,
      anon_sym_AT_LBRACE,
      sym_word,
      sym_non_word,
  [526] = 3,
    ACTIONS(56), 1,
      ts_builtin_sym_end,
    ACTIONS(112), 1,
      anon_sym_EQ,
    ACTIONS(110), 9,
      anon_sym_ATpage,
      anon_sym_LT,
      anon_sym_LT_SLASH,
      anon_sym_AT,
      anon_sym_ATif,
      anon_sym_ATwhile,
      anon_sym_AT_LBRACE,
      sym_word,
      sym_non_word,
  [544] = 2,
    ACTIONS(114), 1,
      ts_builtin_sym_end,
    ACTIONS(116), 9,
      anon_sym_ATpage,
      anon_sym_LT,
      anon_sym_LT_SLASH,
      anon_sym_AT,
      anon_sym_ATif,
      anon_sym_ATwhile,
      anon_sym_AT_LBRACE,
      sym_word,
      sym_non_word,
  [559] = 2,
    ACTIONS(118), 1,
      ts_builtin_sym_end,
    ACTIONS(120), 9,
      anon_sym_ATpage,
      anon_sym_LT,
      anon_sym_LT_SLASH,
      anon_sym_AT,
      anon_sym_ATif,
      anon_sym_ATwhile,
      anon_sym_AT_LBRACE,
      sym_word,
      sym_non_word,
  [574] = 2,
    ACTIONS(122), 1,
      ts_builtin_sym_end,
    ACTIONS(124), 9,
      anon_sym_ATpage,
      anon_sym_LT,
      anon_sym_LT_SLASH,
      anon_sym_AT,
      anon_sym_ATif,
      anon_sym_ATwhile,
      anon_sym_AT_LBRACE,
      sym_word,
      sym_non_word,
  [589] = 2,
    ACTIONS(126), 1,
      ts_builtin_sym_end,
    ACTIONS(128), 9,
      anon_sym_ATpage,
      anon_sym_LT,
      anon_sym_LT_SLASH,
      anon_sym_AT,
      anon_sym_ATif,
      anon_sym_ATwhile,
      anon_sym_AT_LBRACE,
      sym_word,
      sym_non_word,
  [604] = 2,
    ACTIONS(130), 1,
      ts_builtin_sym_end,
    ACTIONS(132), 9,
      anon_sym_ATpage,
      anon_sym_LT,
      anon_sym_LT_SLASH,
      anon_sym_AT,
      anon_sym_ATif,
      anon_sym_ATwhile,
      anon_sym_AT_LBRACE,
      sym_word,
      sym_non_word,
  [619] = 2,
    ACTIONS(134), 1,
      ts_builtin_sym_end,
    ACTIONS(136), 9,
      anon_sym_ATpage,
      anon_sym_LT,
      anon_sym_LT_SLASH,
      anon_sym_AT,
      anon_sym_ATif,
      anon_sym_ATwhile,
      anon_sym_AT_LBRACE,
      sym_word,
      sym_non_word,
  [634] = 2,
    ACTIONS(138), 1,
      ts_builtin_sym_end,
    ACTIONS(140), 9,
      anon_sym_ATpage,
      anon_sym_LT,
      anon_sym_LT_SLASH,
      anon_sym_AT,
      anon_sym_ATif,
      anon_sym_ATwhile,
      anon_sym_AT_LBRACE,
      sym_word,
      sym_non_word,
  [649] = 2,
    ACTIONS(142), 1,
      ts_builtin_sym_end,
    ACTIONS(144), 9,
      anon_sym_ATpage,
      anon_sym_LT,
      anon_sym_LT_SLASH,
      anon_sym_AT,
      anon_sym_ATif,
      anon_sym_ATwhile,
      anon_sym_AT_LBRACE,
      sym_word,
      sym_non_word,
  [664] = 2,
    ACTIONS(146), 1,
      ts_builtin_sym_end,
    ACTIONS(148), 9,
      anon_sym_ATpage,
      anon_sym_LT,
      anon_sym_LT_SLASH,
      anon_sym_AT,
      anon_sym_ATif,
      anon_sym_ATwhile,
      anon_sym_AT_LBRACE,
      sym_word,
      sym_non_word,
  [679] = 2,
    ACTIONS(150), 1,
      ts_builtin_sym_end,
    ACTIONS(152), 9,
      anon_sym_ATpage,
      anon_sym_LT,
      anon_sym_LT_SLASH,
      anon_sym_AT,
      anon_sym_ATif,
      anon_sym_ATwhile,
      anon_sym_AT_LBRACE,
      sym_word,
      sym_non_word,
  [694] = 2,
    ACTIONS(154), 1,
      ts_builtin_sym_end,
    ACTIONS(156), 9,
      anon_sym_ATpage,
      anon_sym_LT,
      anon_sym_LT_SLASH,
      anon_sym_AT,
      anon_sym_ATif,
      anon_sym_ATwhile,
      anon_sym_AT_LBRACE,
      sym_word,
      sym_non_word,
  [709] = 2,
    ACTIONS(158), 1,
      ts_builtin_sym_end,
    ACTIONS(160), 9,
      anon_sym_ATpage,
      anon_sym_LT,
      anon_sym_LT_SLASH,
      anon_sym_AT,
      anon_sym_ATif,
      anon_sym_ATwhile,
      anon_sym_AT_LBRACE,
      sym_word,
      sym_non_word,
  [724] = 1,
    ACTIONS(126), 9,
      anon_sym_GT,
      anon_sym_LT_SLASH,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_SEMI,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_COMMA,
      anon_sym_DOT,
  [736] = 5,
    ACTIONS(78), 1,
      aux_sym_route_token1,
    ACTIONS(162), 1,
      anon_sym_RPAREN,
    ACTIONS(164), 1,
      sym_identifier,
    ACTIONS(166), 1,
      sym_number,
    STATE(49), 5,
      sym__expression,
      sym_binary_expression,
      sym_call_expression,
      sym_member_expression,
      sym_string,
  [756] = 5,
    ACTIONS(78), 1,
      aux_sym_route_token1,
    ACTIONS(168), 1,
      anon_sym_RPAREN,
    ACTIONS(170), 1,
      sym_identifier,
    ACTIONS(172), 1,
      sym_number,
    STATE(53), 5,
      sym__expression,
      sym_binary_expression,
      sym_call_expression,
      sym_member_expression,
      sym_string,
  [776] = 1,
    ACTIONS(148), 9,
      anon_sym_ATpage,
      anon_sym_LT,
      anon_sym_LT_SLASH,
      anon_sym_AT,
      anon_sym_ATif,
      anon_sym_ATwhile,
      anon_sym_AT_LBRACE,
      sym_word,
      sym_non_word,
  [788] = 1,
    ACTIONS(136), 9,
      anon_sym_ATpage,
      anon_sym_LT,
      anon_sym_LT_SLASH,
      anon_sym_AT,
      anon_sym_ATif,
      anon_sym_ATwhile,
      anon_sym_AT_LBRACE,
      sym_word,
      sym_non_word,
  [800] = 5,
    ACTIONS(78), 1,
      aux_sym_route_token1,
    ACTIONS(174), 1,
      anon_sym_RPAREN,
    ACTIONS(176), 1,
      sym_identifier,
    ACTIONS(178), 1,
      sym_number,
    STATE(51), 5,
      sym__expression,
      sym_binary_expression,
      sym_call_expression,
      sym_member_expression,
      sym_string,
  [820] = 4,
    ACTIONS(78), 1,
      aux_sym_route_token1,
    ACTIONS(180), 1,
      sym_identifier,
    ACTIONS(182), 1,
      sym_number,
    STATE(54), 5,
      sym__expression,
      sym_binary_expression,
      sym_call_expression,
      sym_member_expression,
      sym_string,
  [837] = 4,
    ACTIONS(78), 1,
      aux_sym_route_token1,
    ACTIONS(184), 1,
      sym_identifier,
    ACTIONS(186), 1,
      sym_number,
    STATE(56), 5,
      sym__expression,
      sym_binary_expression,
      sym_call_expression,
      sym_member_expression,
      sym_string,
  [854] = 4,
    ACTIONS(78), 1,
      aux_sym_route_token1,
    ACTIONS(188), 1,
      sym_identifier,
    ACTIONS(190), 1,
      sym_number,
    STATE(65), 5,
      sym__expression,
      sym_binary_expression,
      sym_call_expression,
      sym_member_expression,
      sym_string,
  [871] = 4,
    ACTIONS(78), 1,
      aux_sym_route_token1,
    ACTIONS(192), 1,
      sym_identifier,
    ACTIONS(194), 1,
      sym_number,
    STATE(64), 5,
      sym__expression,
      sym_binary_expression,
      sym_call_expression,
      sym_member_expression,
      sym_string,
  [888] = 4,
    ACTIONS(78), 1,
      aux_sym_route_token1,
    ACTIONS(196), 1,
      sym_identifier,
    ACTIONS(198), 1,
      sym_number,
    STATE(61), 5,
      sym__expression,
      sym_binary_expression,
      sym_call_expression,
      sym_member_expression,
      sym_string,
  [905] = 4,
    ACTIONS(78), 1,
      aux_sym_route_token1,
    ACTIONS(200), 1,
      sym_identifier,
    ACTIONS(202), 1,
      sym_number,
    STATE(60), 5,
      sym__expression,
      sym_binary_expression,
      sym_call_expression,
      sym_member_expression,
      sym_string,
  [922] = 4,
    ACTIONS(78), 1,
      aux_sym_route_token1,
    ACTIONS(204), 1,
      sym_identifier,
    ACTIONS(206), 1,
      sym_number,
    STATE(63), 5,
      sym__expression,
      sym_binary_expression,
      sym_call_expression,
      sym_member_expression,
      sym_string,
  [939] = 4,
    ACTIONS(78), 1,
      aux_sym_route_token1,
    ACTIONS(208), 1,
      sym_identifier,
    ACTIONS(210), 1,
      sym_number,
    STATE(52), 5,
      sym__expression,
      sym_binary_expression,
      sym_call_expression,
      sym_member_expression,
      sym_string,
  [956] = 4,
    ACTIONS(78), 1,
      aux_sym_route_token1,
    ACTIONS(212), 1,
      sym_identifier,
    ACTIONS(214), 1,
      sym_number,
    STATE(62), 5,
      sym__expression,
      sym_binary_expression,
      sym_call_expression,
      sym_member_expression,
      sym_string,
  [973] = 1,
    ACTIONS(216), 7,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_SEMI,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_COMMA,
      anon_sym_DOT,
  [983] = 1,
    ACTIONS(218), 7,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_SEMI,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_COMMA,
      anon_sym_DOT,
  [993] = 1,
    ACTIONS(220), 7,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_SEMI,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_COMMA,
      anon_sym_DOT,
  [1003] = 6,
    ACTIONS(222), 1,
      anon_sym_LPAREN,
    ACTIONS(224), 1,
      anon_sym_RPAREN,
    ACTIONS(228), 1,
      anon_sym_COMMA,
    ACTIONS(230), 1,
      anon_sym_DOT,
    STATE(72), 1,
      aux_sym_call_expression_repeat1,
    ACTIONS(226), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
  [1023] = 1,
    ACTIONS(232), 7,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_SEMI,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_COMMA,
      anon_sym_DOT,
  [1033] = 6,
    ACTIONS(222), 1,
      anon_sym_LPAREN,
    ACTIONS(228), 1,
      anon_sym_COMMA,
    ACTIONS(230), 1,
      anon_sym_DOT,
    ACTIONS(234), 1,
      anon_sym_RPAREN,
    STATE(69), 1,
      aux_sym_call_expression_repeat1,
    ACTIONS(226), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
  [1053] = 1,
    ACTIONS(236), 7,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_SEMI,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_COMMA,
      anon_sym_DOT,
  [1063] = 6,
    ACTIONS(222), 1,
      anon_sym_LPAREN,
    ACTIONS(228), 1,
      anon_sym_COMMA,
    ACTIONS(230), 1,
      anon_sym_DOT,
    ACTIONS(238), 1,
      anon_sym_RPAREN,
    STATE(71), 1,
      aux_sym_call_expression_repeat1,
    ACTIONS(226), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
  [1083] = 4,
    ACTIONS(222), 1,
      anon_sym_LPAREN,
    ACTIONS(230), 1,
      anon_sym_DOT,
    ACTIONS(226), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(240), 2,
      anon_sym_RPAREN,
      anon_sym_COMMA,
  [1098] = 2,
    ACTIONS(244), 1,
      sym_identifier,
    ACTIONS(242), 5,
      anon_sym_LPAREN,
      anon_sym_SEMI,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_DOT,
  [1109] = 4,
    ACTIONS(222), 1,
      anon_sym_LPAREN,
    ACTIONS(230), 1,
      anon_sym_DOT,
    ACTIONS(246), 1,
      anon_sym_RPAREN,
    ACTIONS(226), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
  [1123] = 4,
    ACTIONS(222), 1,
      anon_sym_LPAREN,
    ACTIONS(230), 1,
      anon_sym_DOT,
    ACTIONS(248), 1,
      anon_sym_SEMI,
    ACTIONS(226), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
  [1137] = 3,
    ACTIONS(250), 1,
      anon_sym_LPAREN,
    ACTIONS(252), 1,
      sym_identifier,
    STATE(76), 3,
      sym__simple_expression,
      sym_simple_call_expression,
      sym_simple_member_expression,
  [1149] = 3,
    ACTIONS(254), 1,
      anon_sym_LPAREN,
    ACTIONS(256), 1,
      sym_identifier,
    STATE(17), 3,
      sym__simple_expression,
      sym_simple_call_expression,
      sym_simple_member_expression,
  [1161] = 4,
    ACTIONS(222), 1,
      anon_sym_LPAREN,
    ACTIONS(230), 1,
      anon_sym_DOT,
    ACTIONS(258), 1,
      anon_sym_RPAREN,
    ACTIONS(226), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
  [1175] = 4,
    ACTIONS(222), 1,
      anon_sym_LPAREN,
    ACTIONS(230), 1,
      anon_sym_DOT,
    ACTIONS(260), 1,
      anon_sym_RPAREN,
    ACTIONS(226), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
  [1189] = 4,
    ACTIONS(222), 1,
      anon_sym_LPAREN,
    ACTIONS(230), 1,
      anon_sym_DOT,
    ACTIONS(262), 1,
      anon_sym_SEMI,
    ACTIONS(226), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
  [1203] = 4,
    ACTIONS(222), 1,
      anon_sym_LPAREN,
    ACTIONS(230), 1,
      anon_sym_DOT,
    ACTIONS(264), 1,
      anon_sym_RPAREN,
    ACTIONS(226), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
  [1217] = 4,
    ACTIONS(222), 1,
      anon_sym_LPAREN,
    ACTIONS(230), 1,
      anon_sym_DOT,
    ACTIONS(266), 1,
      anon_sym_RPAREN,
    ACTIONS(226), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
  [1231] = 4,
    ACTIONS(222), 1,
      anon_sym_LPAREN,
    ACTIONS(230), 1,
      anon_sym_DOT,
    ACTIONS(268), 1,
      anon_sym_RPAREN,
    ACTIONS(226), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
  [1245] = 1,
    ACTIONS(86), 3,
      anon_sym_LT_SLASH,
      anon_sym_LPAREN,
      anon_sym_DOT,
  [1251] = 3,
    ACTIONS(270), 1,
      anon_sym_GT,
    ACTIONS(272), 1,
      sym_word,
    STATE(104), 1,
      sym_attribute,
  [1261] = 1,
    ACTIONS(94), 3,
      anon_sym_LT_SLASH,
      anon_sym_LPAREN,
      anon_sym_DOT,
  [1267] = 3,
    ACTIONS(228), 1,
      anon_sym_COMMA,
    ACTIONS(274), 1,
      anon_sym_RPAREN,
    STATE(73), 1,
      aux_sym_call_expression_repeat1,
  [1277] = 1,
    ACTIONS(90), 3,
      anon_sym_LT_SLASH,
      anon_sym_LPAREN,
      anon_sym_DOT,
  [1283] = 3,
    ACTIONS(228), 1,
      anon_sym_COMMA,
    ACTIONS(276), 1,
      anon_sym_RPAREN,
    STATE(73), 1,
      aux_sym_call_expression_repeat1,
  [1293] = 3,
    ACTIONS(228), 1,
      anon_sym_COMMA,
    ACTIONS(278), 1,
      anon_sym_RPAREN,
    STATE(73), 1,
      aux_sym_call_expression_repeat1,
  [1303] = 3,
    ACTIONS(240), 1,
      anon_sym_RPAREN,
    ACTIONS(280), 1,
      anon_sym_COMMA,
    STATE(73), 1,
      aux_sym_call_expression_repeat1,
  [1313] = 1,
    ACTIONS(98), 3,
      anon_sym_LT_SLASH,
      anon_sym_LPAREN,
      anon_sym_DOT,
  [1319] = 3,
    ACTIONS(272), 1,
      sym_word,
    ACTIONS(283), 1,
      anon_sym_GT,
    STATE(120), 1,
      sym_attribute,
  [1329] = 3,
    ACTIONS(102), 1,
      anon_sym_LT_SLASH,
    ACTIONS(285), 1,
      anon_sym_LPAREN,
    ACTIONS(287), 1,
      anon_sym_DOT,
  [1339] = 2,
    ACTIONS(289), 1,
      anon_sym_LT_SLASH,
    STATE(85), 1,
      sym_end_tag,
  [1346] = 1,
    ACTIONS(138), 2,
      anon_sym_GT,
      anon_sym_LT_SLASH,
  [1351] = 2,
    ACTIONS(291), 1,
      aux_sym_route_token1,
    STATE(25), 1,
      sym_string,
  [1358] = 2,
    ACTIONS(293), 1,
      anon_sym_LT_SLASH,
    STATE(23), 1,
      sym_end_tag,
  [1365] = 2,
    ACTIONS(295), 1,
      aux_sym_route_token1,
    STATE(28), 1,
      sym_route,
  [1372] = 2,
    ACTIONS(297), 1,
      anon_sym_EQ,
    ACTIONS(299), 1,
      anon_sym_SEMI,
  [1379] = 2,
    ACTIONS(56), 1,
      anon_sym_LT_SLASH,
    ACTIONS(301), 1,
      anon_sym_EQ,
  [1386] = 2,
    ACTIONS(303), 1,
      aux_sym_route_token1,
    STATE(78), 1,
      sym_string,
  [1393] = 1,
    ACTIONS(130), 2,
      anon_sym_LT_SLASH,
      anon_sym_RBRACE,
  [1398] = 1,
    ACTIONS(158), 2,
      anon_sym_LT_SLASH,
      anon_sym_RBRACE,
  [1403] = 2,
    ACTIONS(305), 1,
      aux_sym_route_token1,
    STATE(122), 1,
      sym_route,
  [1410] = 1,
    ACTIONS(307), 1,
      anon_sym_RBRACE,
  [1414] = 1,
    ACTIONS(309), 1,
      sym_identifier,
  [1418] = 1,
    ACTIONS(114), 1,
      anon_sym_LT_SLASH,
  [1422] = 1,
    ACTIONS(311), 1,
      anon_sym_RBRACE,
  [1426] = 1,
    ACTIONS(142), 1,
      anon_sym_LT_SLASH,
  [1430] = 1,
    ACTIONS(313), 1,
      anon_sym_RBRACE,
  [1434] = 1,
    ACTIONS(315), 1,
      anon_sym_RBRACE,
  [1438] = 1,
    ACTIONS(317), 1,
      sym_identifier,
  [1442] = 1,
    ACTIONS(319), 1,
      anon_sym_RBRACE,
  [1446] = 1,
    ACTIONS(118), 1,
      anon_sym_LT_SLASH,
  [1450] = 1,
    ACTIONS(122), 1,
      anon_sym_LT_SLASH,
  [1454] = 1,
    ACTIONS(321), 1,
      anon_sym_LBRACE,
  [1458] = 1,
    ACTIONS(323), 1,
      anon_sym_LBRACE,
  [1462] = 1,
    ACTIONS(325), 1,
      anon_sym_GT,
  [1466] = 1,
    ACTIONS(327), 1,
      anon_sym_GT,
  [1470] = 1,
    ACTIONS(329), 1,
      anon_sym_RBRACE,
  [1474] = 1,
    ACTIONS(331), 1,
      anon_sym_GT,
  [1478] = 1,
    ACTIONS(333), 1,
      ts_builtin_sym_end,
  [1482] = 1,
    ACTIONS(335), 1,
      anon_sym_LPAREN,
  [1486] = 1,
    ACTIONS(337), 1,
      anon_sym_LPAREN,
  [1490] = 1,
    ACTIONS(339), 1,
      sym_identifier,
  [1494] = 1,
    ACTIONS(341), 1,
      anon_sym_RBRACE,
  [1498] = 1,
    ACTIONS(343), 1,
      anon_sym_RBRACE,
  [1502] = 1,
    ACTIONS(345), 1,
      anon_sym_RBRACE,
  [1506] = 1,
    ACTIONS(347), 1,
      sym_tag_name,
  [1510] = 1,
    ACTIONS(349), 1,
      sym_tag_name,
  [1514] = 1,
    ACTIONS(351), 1,
      sym_tag_name,
  [1518] = 1,
    ACTIONS(353), 1,
      sym_identifier,
  [1522] = 1,
    ACTIONS(355), 1,
      sym_tag_name,
  [1526] = 1,
    ACTIONS(357), 1,
      sym_identifier,
  [1530] = 1,
    ACTIONS(359), 1,
      anon_sym_LBRACE,
  [1534] = 1,
    ACTIONS(361), 1,
      anon_sym_LBRACE,
  [1538] = 1,
    ACTIONS(363), 1,
      anon_sym_GT,
  [1542] = 1,
    ACTIONS(301), 1,
      anon_sym_EQ,
  [1546] = 1,
    ACTIONS(150), 1,
      anon_sym_LT_SLASH,
  [1550] = 1,
    ACTIONS(154), 1,
      anon_sym_LT_SLASH,
  [1554] = 1,
    ACTIONS(365), 1,
      anon_sym_LPAREN,
  [1558] = 1,
    ACTIONS(367), 1,
      anon_sym_LPAREN,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 46,
  [SMALL_STATE(4)] = 92,
  [SMALL_STATE(5)] = 137,
  [SMALL_STATE(6)] = 179,
  [SMALL_STATE(7)] = 221,
  [SMALL_STATE(8)] = 257,
  [SMALL_STATE(9)] = 293,
  [SMALL_STATE(10)] = 329,
  [SMALL_STATE(11)] = 365,
  [SMALL_STATE(12)] = 401,
  [SMALL_STATE(13)] = 437,
  [SMALL_STATE(14)] = 454,
  [SMALL_STATE(15)] = 471,
  [SMALL_STATE(16)] = 488,
  [SMALL_STATE(17)] = 505,
  [SMALL_STATE(18)] = 526,
  [SMALL_STATE(19)] = 544,
  [SMALL_STATE(20)] = 559,
  [SMALL_STATE(21)] = 574,
  [SMALL_STATE(22)] = 589,
  [SMALL_STATE(23)] = 604,
  [SMALL_STATE(24)] = 619,
  [SMALL_STATE(25)] = 634,
  [SMALL_STATE(26)] = 649,
  [SMALL_STATE(27)] = 664,
  [SMALL_STATE(28)] = 679,
  [SMALL_STATE(29)] = 694,
  [SMALL_STATE(30)] = 709,
  [SMALL_STATE(31)] = 724,
  [SMALL_STATE(32)] = 736,
  [SMALL_STATE(33)] = 756,
  [SMALL_STATE(34)] = 776,
  [SMALL_STATE(35)] = 788,
  [SMALL_STATE(36)] = 800,
  [SMALL_STATE(37)] = 820,
  [SMALL_STATE(38)] = 837,
  [SMALL_STATE(39)] = 854,
  [SMALL_STATE(40)] = 871,
  [SMALL_STATE(41)] = 888,
  [SMALL_STATE(42)] = 905,
  [SMALL_STATE(43)] = 922,
  [SMALL_STATE(44)] = 939,
  [SMALL_STATE(45)] = 956,
  [SMALL_STATE(46)] = 973,
  [SMALL_STATE(47)] = 983,
  [SMALL_STATE(48)] = 993,
  [SMALL_STATE(49)] = 1003,
  [SMALL_STATE(50)] = 1023,
  [SMALL_STATE(51)] = 1033,
  [SMALL_STATE(52)] = 1053,
  [SMALL_STATE(53)] = 1063,
  [SMALL_STATE(54)] = 1083,
  [SMALL_STATE(55)] = 1098,
  [SMALL_STATE(56)] = 1109,
  [SMALL_STATE(57)] = 1123,
  [SMALL_STATE(58)] = 1137,
  [SMALL_STATE(59)] = 1149,
  [SMALL_STATE(60)] = 1161,
  [SMALL_STATE(61)] = 1175,
  [SMALL_STATE(62)] = 1189,
  [SMALL_STATE(63)] = 1203,
  [SMALL_STATE(64)] = 1217,
  [SMALL_STATE(65)] = 1231,
  [SMALL_STATE(66)] = 1245,
  [SMALL_STATE(67)] = 1251,
  [SMALL_STATE(68)] = 1261,
  [SMALL_STATE(69)] = 1267,
  [SMALL_STATE(70)] = 1277,
  [SMALL_STATE(71)] = 1283,
  [SMALL_STATE(72)] = 1293,
  [SMALL_STATE(73)] = 1303,
  [SMALL_STATE(74)] = 1313,
  [SMALL_STATE(75)] = 1319,
  [SMALL_STATE(76)] = 1329,
  [SMALL_STATE(77)] = 1339,
  [SMALL_STATE(78)] = 1346,
  [SMALL_STATE(79)] = 1351,
  [SMALL_STATE(80)] = 1358,
  [SMALL_STATE(81)] = 1365,
  [SMALL_STATE(82)] = 1372,
  [SMALL_STATE(83)] = 1379,
  [SMALL_STATE(84)] = 1386,
  [SMALL_STATE(85)] = 1393,
  [SMALL_STATE(86)] = 1398,
  [SMALL_STATE(87)] = 1403,
  [SMALL_STATE(88)] = 1410,
  [SMALL_STATE(89)] = 1414,
  [SMALL_STATE(90)] = 1418,
  [SMALL_STATE(91)] = 1422,
  [SMALL_STATE(92)] = 1426,
  [SMALL_STATE(93)] = 1430,
  [SMALL_STATE(94)] = 1434,
  [SMALL_STATE(95)] = 1438,
  [SMALL_STATE(96)] = 1442,
  [SMALL_STATE(97)] = 1446,
  [SMALL_STATE(98)] = 1450,
  [SMALL_STATE(99)] = 1454,
  [SMALL_STATE(100)] = 1458,
  [SMALL_STATE(101)] = 1462,
  [SMALL_STATE(102)] = 1466,
  [SMALL_STATE(103)] = 1470,
  [SMALL_STATE(104)] = 1474,
  [SMALL_STATE(105)] = 1478,
  [SMALL_STATE(106)] = 1482,
  [SMALL_STATE(107)] = 1486,
  [SMALL_STATE(108)] = 1490,
  [SMALL_STATE(109)] = 1494,
  [SMALL_STATE(110)] = 1498,
  [SMALL_STATE(111)] = 1502,
  [SMALL_STATE(112)] = 1506,
  [SMALL_STATE(113)] = 1510,
  [SMALL_STATE(114)] = 1514,
  [SMALL_STATE(115)] = 1518,
  [SMALL_STATE(116)] = 1522,
  [SMALL_STATE(117)] = 1526,
  [SMALL_STATE(118)] = 1530,
  [SMALL_STATE(119)] = 1534,
  [SMALL_STATE(120)] = 1538,
  [SMALL_STATE(121)] = 1542,
  [SMALL_STATE(122)] = 1546,
  [SMALL_STATE(123)] = 1550,
  [SMALL_STATE(124)] = 1554,
  [SMALL_STATE(125)] = 1558,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document, 0),
  [5] = {.entry = {.count = 1, .reusable = false}}, SHIFT(81),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(116),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(114),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(59),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(106),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(107),
  [17] = {.entry = {.count = 1, .reusable = false}}, SHIFT(7),
  [19] = {.entry = {.count = 1, .reusable = false}}, SHIFT(18),
  [21] = {.entry = {.count = 1, .reusable = false}}, SHIFT(2),
  [23] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document, 1),
  [25] = {.entry = {.count = 1, .reusable = false}}, SHIFT(3),
  [27] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2),
  [29] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2), SHIFT_REPEAT(81),
  [32] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2), SHIFT_REPEAT(116),
  [35] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2), SHIFT_REPEAT(114),
  [38] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2), SHIFT_REPEAT(59),
  [41] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2), SHIFT_REPEAT(106),
  [44] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2), SHIFT_REPEAT(107),
  [47] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2), SHIFT_REPEAT(7),
  [50] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2), SHIFT_REPEAT(18),
  [53] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2), SHIFT_REPEAT(3),
  [56] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__markup, 1),
  [58] = {.entry = {.count = 1, .reusable = false}}, SHIFT(87),
  [60] = {.entry = {.count = 1, .reusable = false}}, SHIFT(112),
  [62] = {.entry = {.count = 1, .reusable = false}}, SHIFT(113),
  [64] = {.entry = {.count = 1, .reusable = false}}, SHIFT(58),
  [66] = {.entry = {.count = 1, .reusable = false}}, SHIFT(124),
  [68] = {.entry = {.count = 1, .reusable = false}}, SHIFT(125),
  [70] = {.entry = {.count = 1, .reusable = false}}, SHIFT(10),
  [72] = {.entry = {.count = 1, .reusable = false}}, SHIFT(83),
  [74] = {.entry = {.count = 1, .reusable = false}}, SHIFT(80),
  [76] = {.entry = {.count = 1, .reusable = false}}, SHIFT(77),
  [78] = {.entry = {.count = 1, .reusable = false}}, SHIFT(31),
  [80] = {.entry = {.count = 1, .reusable = false}}, SHIFT(95),
  [82] = {.entry = {.count = 1, .reusable = false}}, SHIFT(55),
  [84] = {.entry = {.count = 1, .reusable = false}}, SHIFT(57),
  [86] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_simple_call_expression, 5),
  [88] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_simple_call_expression, 5),
  [90] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_simple_member_expression, 3),
  [92] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_simple_member_expression, 3),
  [94] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_simple_call_expression, 4),
  [96] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_simple_call_expression, 4),
  [98] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_simple_call_expression, 3),
  [100] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_simple_call_expression, 3),
  [102] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_interpolated_expression, 2),
  [104] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_interpolated_expression, 2),
  [106] = {.entry = {.count = 1, .reusable = false}}, SHIFT(36),
  [108] = {.entry = {.count = 1, .reusable = false}}, SHIFT(115),
  [110] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__markup, 1),
  [112] = {.entry = {.count = 1, .reusable = false}}, SHIFT(79),
  [114] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_interpolated_code_block, 3),
  [116] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_interpolated_code_block, 3),
  [118] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_interpolated_if_statement, 7),
  [120] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_interpolated_if_statement, 7),
  [122] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_interpolated_while_statement, 7),
  [124] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_interpolated_while_statement, 7),
  [126] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 1),
  [128] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string, 1),
  [130] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_element, 3),
  [132] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_element, 3),
  [134] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_start_tag, 4),
  [136] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_start_tag, 4),
  [138] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_attribute, 3),
  [140] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_attribute, 3),
  [142] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_interpolated_expression, 4),
  [144] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_interpolated_expression, 4),
  [146] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_start_tag, 3),
  [148] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_start_tag, 3),
  [150] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_route_declaration, 2),
  [152] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_route_declaration, 2),
  [154] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_route, 1),
  [156] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_route, 1),
  [158] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_end_tag, 3),
  [160] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_end_tag, 3),
  [162] = {.entry = {.count = 1, .reusable = false}}, SHIFT(74),
  [164] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [166] = {.entry = {.count = 1, .reusable = false}}, SHIFT(49),
  [168] = {.entry = {.count = 1, .reusable = false}}, SHIFT(46),
  [170] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [172] = {.entry = {.count = 1, .reusable = false}}, SHIFT(53),
  [174] = {.entry = {.count = 1, .reusable = false}}, SHIFT(16),
  [176] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [178] = {.entry = {.count = 1, .reusable = false}}, SHIFT(51),
  [180] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [182] = {.entry = {.count = 1, .reusable = false}}, SHIFT(54),
  [184] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [186] = {.entry = {.count = 1, .reusable = false}}, SHIFT(56),
  [188] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [190] = {.entry = {.count = 1, .reusable = false}}, SHIFT(65),
  [192] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [194] = {.entry = {.count = 1, .reusable = false}}, SHIFT(64),
  [196] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [198] = {.entry = {.count = 1, .reusable = false}}, SHIFT(61),
  [200] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [202] = {.entry = {.count = 1, .reusable = false}}, SHIFT(60),
  [204] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [206] = {.entry = {.count = 1, .reusable = false}}, SHIFT(63),
  [208] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [210] = {.entry = {.count = 1, .reusable = false}}, SHIFT(52),
  [212] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [214] = {.entry = {.count = 1, .reusable = false}}, SHIFT(62),
  [216] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_call_expression, 3),
  [218] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_call_expression, 5),
  [220] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_call_expression, 4),
  [222] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [224] = {.entry = {.count = 1, .reusable = true}}, SHIFT(68),
  [226] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [228] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [230] = {.entry = {.count = 1, .reusable = true}}, SHIFT(108),
  [232] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_member_expression, 3),
  [234] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [236] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_binary_expression, 3),
  [238] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [240] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_call_expression_repeat1, 2),
  [242] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__expression, 1),
  [244] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_type_specifier, 1),
  [246] = {.entry = {.count = 1, .reusable = true}}, SHIFT(100),
  [248] = {.entry = {.count = 1, .reusable = true}}, SHIFT(109),
  [250] = {.entry = {.count = 1, .reusable = false}}, SHIFT(42),
  [252] = {.entry = {.count = 1, .reusable = true}}, SHIFT(76),
  [254] = {.entry = {.count = 1, .reusable = false}}, SHIFT(43),
  [256] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [258] = {.entry = {.count = 1, .reusable = true}}, SHIFT(92),
  [260] = {.entry = {.count = 1, .reusable = true}}, SHIFT(99),
  [262] = {.entry = {.count = 1, .reusable = true}}, SHIFT(91),
  [264] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [266] = {.entry = {.count = 1, .reusable = true}}, SHIFT(118),
  [268] = {.entry = {.count = 1, .reusable = true}}, SHIFT(119),
  [270] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [272] = {.entry = {.count = 1, .reusable = true}}, SHIFT(121),
  [274] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [276] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [278] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [280] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_call_expression_repeat1, 2), SHIFT_REPEAT(37),
  [283] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [285] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [287] = {.entry = {.count = 1, .reusable = true}}, SHIFT(89),
  [289] = {.entry = {.count = 1, .reusable = true}}, SHIFT(113),
  [291] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [293] = {.entry = {.count = 1, .reusable = true}}, SHIFT(114),
  [295] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [297] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [299] = {.entry = {.count = 1, .reusable = true}}, SHIFT(96),
  [301] = {.entry = {.count = 1, .reusable = true}}, SHIFT(84),
  [303] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [305] = {.entry = {.count = 1, .reusable = true}}, SHIFT(123),
  [307] = {.entry = {.count = 1, .reusable = true}}, SHIFT(90),
  [309] = {.entry = {.count = 1, .reusable = true}}, SHIFT(70),
  [311] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_variable_declaration, 5),
  [313] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [315] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [317] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type_specifier, 1),
  [319] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_variable_declaration, 3),
  [321] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [323] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [325] = {.entry = {.count = 1, .reusable = true}}, SHIFT(86),
  [327] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [329] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [331] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [333] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [335] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [337] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [339] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [341] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression_statement, 2),
  [343] = {.entry = {.count = 1, .reusable = true}}, SHIFT(97),
  [345] = {.entry = {.count = 1, .reusable = true}}, SHIFT(98),
  [347] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [349] = {.entry = {.count = 1, .reusable = true}}, SHIFT(101),
  [351] = {.entry = {.count = 1, .reusable = true}}, SHIFT(102),
  [353] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [355] = {.entry = {.count = 1, .reusable = true}}, SHIFT(75),
  [357] = {.entry = {.count = 1, .reusable = true}}, SHIFT(82),
  [359] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [361] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [363] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [365] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [367] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef _WIN32
#define extern __declspec(dllexport)
#endif

extern const TSLanguage *tree_sitter_razor(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
